useDotenv: true

org: ${env:SLS_ORG}
service: ${env:SLS_SERVICE}

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    TABLE_NAME: ${env:DYNAMODB_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}
  iam:
    role: ${env:AWS_IAM_ROLE}


functions:
  createAccount:
    handler: functions/createAccount/index.handler
    events:
      - http:
          path: /auth/register
          method: post

  logIn:
    handler: functions/logIn/index.handler
    events:
      - http:
          path: /auth/login
          method: post

  createQuiz:
    handler: functions/createQuiz/index.handler
    events:
      - http:
          path: /quizzes
          method: post

  createQuestions:
    handler: functions/createQuestion/index.handler
    events:
      - http:
          path: /quizzes/{quizId}/questions
          method: post
      
  deleteQuiz:
    handler: functions/deleteQuiz/index.handler
    events:
      - http:
          path: /quizzes/{quizId}
          method: delete

  getAllQuizzes:
    handler: functions/getAllQuizzes/index.handler
    events:
      - http:
          path: /quizzes/
          method: get

  getQuizById:
    handler: functions/getQuizById/index.handler
    events:
      - http:
          path: /quizzes/{quizId}
          method: get

resources:
  Resources:
    QuiztopiaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: GSI1pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1 #all quizzes
            KeySchema:
              - AttributeName: GSI1pk
                KeyType: HASH
            Projection:
              ProjectionType: ALL